### ISSUE TITLE
Dockerfile of gfoidl/dotnet-mono

### ISSUE THREAD

**Issue by jrichardsz** [gfoidl/Dockerfiles#1]
Hi.

Is this your docker image https://hub.docker.com/r/gfoidl/dotnet-mono ?

If it is your, awesome work!!

Could you please to share the Dockerfile?

If not, Could you share me some links to install netframework 4.5 in linux?

I'm able to run netcore apps with dotnet or mono, but install netframework 4.5 is a pain...

Thanks in advance

**Comment by gfoidl** [comment]
> Could you please to share the Dockerfile?

https://github.com/gfoidl/Dockerfiles/blob/master/dotnet-mono/Dockerfile

> install netframework 4.5 in linux

.NET Framework 4.5 is for Windows only, that's why Mono exists. I.e. with Mono you can run .NET 4.5 apps on non-Windows OS too.

**Comment by jrichardsz** [comment]
Thanks man.

Also I think your image is the only with net 2.2 because if I try to pull it, I have an error

````
Unable to find image 'microsoft/dotnet:2.2-sdk' locally
docker: Error response from daemon: Head "https://registry-1.docker.io/v2/microsoft/dotnet/manifests/2.2-sdk": Get "https://auth.docker.io/token?account=FOO&scope=repository%3Amicrosoft%2Fdotnet%3Apull&service=registry.docker.io": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
```

Other images can be pulled without problems.
